"""Trainable recurrent manifold graph interpreter and deterministic controller."""

from .baselines import FlatTransformerScorer, PooledScorer
from .calibration import (
    EvidenceCalibration,
    PrecisionRecallPoint,
    binary_average_precision,
    calibrate_evidence_threshold,
    precision_recall_curve,
)
from .calibration_v0_3 import (
    ClosedLoopEvidenceCalibration,
    ExactSetOperatingPoint,
    TemperatureScalingResult,
    calibrate_closed_loop_evidence,
    fit_temperature_scaling,
)
from .config import SparseControllerConfig, SpiderModelConfig
from .controller import (
    ActionDiagnostic,
    ActionSchedule,
    ActionSource,
    ContextLedgerEntry,
    ControllerActionSelection,
    ControllerActions,
    ControllerProposal,
    ControllerResult,
    ControllerRoundRecord,
    ControllerState,
    ControllerStep,
    ControllerTransition,
    EvidenceLedgerEntry,
    SparseWavefrontController,
    TraceLedgerEntry,
    candidate_control_features,
    stable_candidate_selection,
    termination_control_features,
)
from .hypothesis import HypothesisBatch
from .execution import (
    ControllerExecutionPolicy,
    HorizonMode,
    PathStateIntervention,
    apply_path_state_intervention,
)
from .experiment import (
    ResolvedExperiment,
    build_model,
    load_experiment,
    parameter_count,
)
from .evaluation import EvaluationReport, evaluate_batches
from .evidence_diagnostics import (
    EvidenceCandidateObservation,
    EvidencePipelineCaseReport,
    EvidenceRequirementObservation,
    aggregate_evidence_pipeline,
    observe_evidence_pipeline,
)
from .evaluation_v0_1 import (
    ClosedLoopEvaluationReport,
    calibrate_on_development_batches,
    execute_closed_loop_case,
    evaluate_closed_loop_batches,
    evaluate_rollout_stress_states,
)
from .losses import (
    CandidateSupervision,
    LossTerm,
    SpiderLossConfig,
    SpiderLossReport,
    behavioural_consistency_loss,
    candidate_loss_report,
    multi_positive_evidence_ranking_loss,
    multi_positive_priority_loss,
    null_expansion_loss_term,
    termination_loss_report,
)
from .model import CandidateScorerBase, SpiderModel
from .protocol_v0_1 import (
    DATASET_VERSION_V0_2,
    SEALED_SPLIT_V0_2,
    SealedEvaluationAuthorization,
    authorize_v0_2_sealed_evaluation,
    validate_v0_1_artifact_input,
    validate_v0_1_split_access,
)
from .protocol_v0_3 import (
    EVIDENCE_DEVELOPMENT_PROTOCOL,
    DevelopmentPartitionManifest,
    GroupedDevelopmentCases,
    GroupedDevelopmentManifest,
    build_grouped_development_cases,
    verify_grouped_development_manifest,
)
from .state_oracle import EvidenceRequirement, StateOracle, StateSupervision
from .terminator import TerminationFactorTargets
from .termination_training import (
    HeadTrainingRecord,
    HeadTrainingResult,
    NullExpansionStateDataset,
    TerminationStateDataset,
    TerminationStateEvaluation,
    collect_termination_state_dataset,
    evaluate_termination_state_dataset,
    train_frozen_null_head,
    train_frozen_termination_head,
)
from .set_attention import (
    AttentionBackendStatus,
    PositionFreeCrossAttention,
    attention_backend_status,
    padded_family_gather,
)
from .types import CandidateOutputs, PaddedSet
from .training import (
    OracleMetrics,
    OracleRollout,
    RolloutRoundDiagnostic,
    TrainingLoopConfig,
    TrainingRecord,
    TrainingResult,
    controller_rollout,
    evaluate_oracle_batches,
    make_tiny_cases,
    mixed_rollout,
    oracle_rollout,
    train_oracle_batches,
)

__all__ = [
    "AttentionBackendStatus",
    "ActionDiagnostic",
    "ActionSchedule",
    "ActionSource",
    "CandidateOutputs",
    "CandidateScorerBase",
    "CandidateSupervision",
    "ClosedLoopEvaluationReport",
    "ClosedLoopEvidenceCalibration",
    "ContextLedgerEntry",
    "ControllerActionSelection",
    "ControllerActions",
    "ControllerExecutionPolicy",
    "ControllerProposal",
    "ControllerResult",
    "ControllerRoundRecord",
    "ControllerState",
    "ControllerStep",
    "ControllerTransition",
    "DATASET_VERSION_V0_2",
    "DevelopmentPartitionManifest",
    "EVIDENCE_DEVELOPMENT_PROTOCOL",
    "EvidenceCalibration",
    "EvidenceCandidateObservation",
    "EvidencePipelineCaseReport",
    "EvidenceRequirement",
    "EvidenceRequirementObservation",
    "ExactSetOperatingPoint",
    "EvidenceLedgerEntry",
    "EvaluationReport",
    "FlatTransformerScorer",
    "GroupedDevelopmentCases",
    "GroupedDevelopmentManifest",
    "HypothesisBatch",
    "HorizonMode",
    "LossTerm",
    "OracleMetrics",
    "OracleRollout",
    "PaddedSet",
    "PathStateIntervention",
    "PooledScorer",
    "PositionFreeCrossAttention",
    "PrecisionRecallPoint",
    "ResolvedExperiment",
    "RolloutRoundDiagnostic",
    "SEALED_SPLIT_V0_2",
    "SealedEvaluationAuthorization",
    "SparseControllerConfig",
    "SparseWavefrontController",
    "SpiderModel",
    "SpiderModelConfig",
    "SpiderLossConfig",
    "SpiderLossReport",
    "StateOracle",
    "StateSupervision",
    "TerminationFactorTargets",
    "TerminationStateDataset",
    "TerminationStateEvaluation",
    "HeadTrainingRecord",
    "HeadTrainingResult",
    "NullExpansionStateDataset",
    "TraceLedgerEntry",
    "TemperatureScalingResult",
    "TrainingLoopConfig",
    "TrainingRecord",
    "TrainingResult",
    "attention_backend_status",
    "aggregate_evidence_pipeline",
    "apply_path_state_intervention",
    "authorize_v0_2_sealed_evaluation",
    "behavioural_consistency_loss",
    "binary_average_precision",
    "build_model",
    "build_grouped_development_cases",
    "calibrate_evidence_threshold",
    "calibrate_closed_loop_evidence",
    "calibrate_on_development_batches",
    "candidate_control_features",
    "candidate_loss_report",
    "controller_rollout",
    "collect_termination_state_dataset",
    "evaluate_oracle_batches",
    "evaluate_batches",
    "evaluate_closed_loop_batches",
    "execute_closed_loop_case",
    "evaluate_rollout_stress_states",
    "evaluate_termination_state_dataset",
    "fit_temperature_scaling",
    "make_tiny_cases",
    "multi_positive_evidence_ranking_loss",
    "multi_positive_priority_loss",
    "mixed_rollout",
    "null_expansion_loss_term",
    "observe_evidence_pipeline",
    "load_experiment",
    "oracle_rollout",
    "parameter_count",
    "padded_family_gather",
    "precision_recall_curve",
    "stable_candidate_selection",
    "termination_control_features",
    "termination_loss_report",
    "train_oracle_batches",
    "train_frozen_null_head",
    "train_frozen_termination_head",
    "validate_v0_1_artifact_input",
    "validate_v0_1_split_access",
    "verify_grouped_development_manifest",
]
