"""Trainable recurrent manifold graph interpreter and deterministic controller."""

from .baselines import FlatTransformerScorer, PooledScorer
from .calibration import (
    EvidenceCalibration,
    PrecisionRecallPoint,
    binary_average_precision,
    calibrate_evidence_threshold,
    precision_recall_curve,
)
from .config import SparseControllerConfig, SpiderModelConfig
from .controller import (
    ActionDiagnostic,
    ActionSchedule,
    ActionSource,
    ContextLedgerEntry,
    ControllerActions,
    ControllerProposal,
    ControllerResult,
    ControllerState,
    ControllerStep,
    ControllerTransition,
    EvidenceLedgerEntry,
    SparseWavefrontController,
    TraceLedgerEntry,
    candidate_control_features,
    stable_candidate_selection,
    termination_control_features,
)
from .hypothesis import HypothesisBatch
from .experiment import (
    ResolvedExperiment,
    build_model,
    load_experiment,
    parameter_count,
)
from .evaluation import EvaluationReport, evaluate_batches
from .evaluation_v0_1 import (
    ClosedLoopEvaluationReport,
    calibrate_on_development_batches,
    evaluate_closed_loop_batches,
    evaluate_rollout_stress_states,
)
from .losses import (
    CandidateSupervision,
    LossTerm,
    SpiderLossConfig,
    SpiderLossReport,
    behavioural_consistency_loss,
    candidate_loss_report,
    multi_positive_priority_loss,
    termination_loss_report,
)
from .model import CandidateScorerBase, SpiderModel
from .protocol_v0_1 import (
    DATASET_VERSION_V0_2,
    SEALED_SPLIT_V0_2,
    SealedEvaluationAuthorization,
    authorize_v0_2_sealed_evaluation,
    validate_v0_1_artifact_input,
    validate_v0_1_split_access,
)
from .state_oracle import StateOracle, StateSupervision
from .set_attention import (
    AttentionBackendStatus,
    PositionFreeCrossAttention,
    attention_backend_status,
    padded_family_gather,
)
from .types import CandidateOutputs, PaddedSet
from .training import (
    OracleMetrics,
    OracleRollout,
    RolloutRoundDiagnostic,
    TrainingLoopConfig,
    TrainingRecord,
    TrainingResult,
    controller_rollout,
    evaluate_oracle_batches,
    make_tiny_cases,
    mixed_rollout,
    oracle_rollout,
    train_oracle_batches,
)

__all__ = [
    "AttentionBackendStatus",
    "ActionDiagnostic",
    "ActionSchedule",
    "ActionSource",
    "CandidateOutputs",
    "CandidateScorerBase",
    "CandidateSupervision",
    "ClosedLoopEvaluationReport",
    "ContextLedgerEntry",
    "ControllerActions",
    "ControllerProposal",
    "ControllerResult",
    "ControllerState",
    "ControllerStep",
    "ControllerTransition",
    "DATASET_VERSION_V0_2",
    "EvidenceCalibration",
    "EvidenceLedgerEntry",
    "EvaluationReport",
    "FlatTransformerScorer",
    "HypothesisBatch",
    "LossTerm",
    "OracleMetrics",
    "OracleRollout",
    "PaddedSet",
    "PooledScorer",
    "PositionFreeCrossAttention",
    "PrecisionRecallPoint",
    "ResolvedExperiment",
    "RolloutRoundDiagnostic",
    "SEALED_SPLIT_V0_2",
    "SealedEvaluationAuthorization",
    "SparseControllerConfig",
    "SparseWavefrontController",
    "SpiderModel",
    "SpiderModelConfig",
    "SpiderLossConfig",
    "SpiderLossReport",
    "StateOracle",
    "StateSupervision",
    "TraceLedgerEntry",
    "TrainingLoopConfig",
    "TrainingRecord",
    "TrainingResult",
    "attention_backend_status",
    "authorize_v0_2_sealed_evaluation",
    "behavioural_consistency_loss",
    "binary_average_precision",
    "build_model",
    "calibrate_evidence_threshold",
    "calibrate_on_development_batches",
    "candidate_control_features",
    "candidate_loss_report",
    "controller_rollout",
    "evaluate_oracle_batches",
    "evaluate_batches",
    "evaluate_closed_loop_batches",
    "evaluate_rollout_stress_states",
    "make_tiny_cases",
    "multi_positive_priority_loss",
    "mixed_rollout",
    "load_experiment",
    "oracle_rollout",
    "parameter_count",
    "padded_family_gather",
    "precision_recall_curve",
    "stable_candidate_selection",
    "termination_control_features",
    "termination_loss_report",
    "train_oracle_batches",
    "validate_v0_1_artifact_input",
    "validate_v0_1_split_access",
]
